import { toast } from './Toast';

interface ScorecardData {
  text: string;
  score: number;
  grade: string;
  gradeColor: string;
  checks: { label: string; passed: boolean; points: number }[];
  penalties: { label: string; points: number }[];
}

function getGradeEmoji(grade: string): string {
  if (grade === 'A+' || grade === 'A') return '🔥';
  if (grade === 'B') return '💪';
  if (grade === 'C') return '⚡';
  return '⚠️';
}

export function exportScorecard(data: ScorecardData): void {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d')!;

  const W = 800;
  const padX = 40;
  const lineItems = [
    ...data.checks.map(c => ({ label: c.label, passed: c.passed, pts: c.passed ? `+${c.points}` : '0' })),
    ...data.penalties.map(p => ({ label: p.label, passed: false, pts: `${p.points}` })),
  ];
  const listH = lineItems.length * 28;
  const tweetBoxH = Math.max(60, Math.min(140, Math.ceil(data.text.length / 60) * 22 + 30));
  const H = 120 + tweetBoxH + 30 + 120 + 20 + listH + 80;

  canvas.width = W * 2; // 2x for retina
  canvas.height = H * 2;
  ctx.scale(2, 2);

  // Background gradient
  const grad = ctx.createLinearGradient(0, 0, W, H);
  grad.addColorStop(0, '#0C0C0E');
  grad.addColorStop(1, '#14141A');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, W, H);

  // Subtle border
  ctx.strokeStyle = '#2A2A2A';
  ctx.lineWidth = 1;
  ctx.roundRect(8, 8, W - 16, H - 16, 16);
  ctx.stroke();

  // Header
  let y = 40;
  ctx.font = 'bold 20px Inter, system-ui, sans-serif';
  ctx.fillStyle = '#FFFFFF';
  ctx.fillText('⚡ X Algorithm Toolkit', padX, y);
  ctx.font = '12px Inter, system-ui, sans-serif';
  ctx.fillStyle = '#666666';
  ctx.fillText('by @Mr_Chartist • Powered by X\'s open-source algorithm', padX, y + 20);
  y += 50;

  // Tweet content box
  ctx.fillStyle = '#1A1A1A';
  ctx.beginPath();
  ctx.roundRect(padX, y, W - padX * 2, tweetBoxH, 10);
  ctx.fill();
  ctx.strokeStyle = '#2A2A2A';
  ctx.lineWidth = 1;
  ctx.stroke();

  ctx.font = '13px Inter, system-ui, sans-serif';
  ctx.fillStyle = '#CCCCCC';
  const words = data.text.split(' ');
  let line = '';
  let lineY = y + 22;
  const maxLineWidth = W - padX * 2 - 28;
  for (const word of words) {
    const test = line + (line ? ' ' : '') + word;
    if (ctx.measureText(test).width > maxLineWidth && line) {
      ctx.fillText(line, padX + 14, lineY);
      line = word;
      lineY += 20;
      if (lineY > y + tweetBoxH - 10) { ctx.fillText('...', padX + 14, lineY); break; }
    } else {
      line = test;
    }
  }
  if (line && lineY <= y + tweetBoxH - 10) ctx.fillText(line, padX + 14, lineY);
  y += tweetBoxH + 30;

  // Score circle
  const cx = W / 2;
  const radius = 42;
  ctx.beginPath();
  ctx.arc(cx, y + radius, radius, 0, Math.PI * 2);
  ctx.fillStyle = '#1A1A1A';
  ctx.fill();
  ctx.strokeStyle = data.gradeColor + '60';
  ctx.lineWidth = 3;
  ctx.stroke();

  // Score arc (progress)
  const progress = Math.min(data.score / 100, 1);
  ctx.beginPath();
  ctx.arc(cx, y + radius, radius, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * progress);
  ctx.strokeStyle = data.gradeColor;
  ctx.lineWidth = 4;
  ctx.stroke();

  // Score number
  ctx.font = 'bold 32px "JetBrains Mono", monospace';
  ctx.fillStyle = data.gradeColor;
  ctx.textAlign = 'center';
  ctx.fillText(String(data.score), cx, y + radius + 10);
  ctx.font = '10px Inter, system-ui, sans-serif';
  ctx.fillStyle = '#888888';
  ctx.fillText('SCORE / 100', cx, y + radius + 24);
  // Grade badge
  ctx.font = 'bold 12px Inter, system-ui, sans-serif';
  ctx.fillStyle = data.gradeColor;
  ctx.fillText(`${getGradeEmoji(data.grade)} Grade ${data.grade}`, cx, y + radius + 42);

  ctx.textAlign = 'left';
  y += radius * 2 + 56;

  // Divider
  ctx.fillStyle = '#2A2A2A';
  ctx.fillRect(padX, y, W - padX * 2, 1);
  y += 16;

  // Checks list
  for (const item of lineItems) {
    const icon = item.passed ? '✅' : '❌';
    ctx.font = '12px Inter, system-ui, sans-serif';
    ctx.fillStyle = '#FFFFFF';
    ctx.fillText(icon, padX, y);
    ctx.fillStyle = item.passed ? '#CCCCCC' : '#888888';
    ctx.fillText(item.label, padX + 24, y);
    ctx.textAlign = 'right';
    ctx.font = 'bold 11px "JetBrains Mono", monospace';
    ctx.fillStyle = item.passed ? '#22C55E' : item.pts.startsWith('-') ? '#EF4444' : '#444444';
    ctx.fillText(item.pts, W - padX, y);
    ctx.textAlign = 'left';
    y += 28;
  }

  // Footer
  y += 20;
  ctx.fillStyle = '#2A2A2A';
  ctx.fillRect(padX, y, W - padX * 2, 1);
  y += 16;
  ctx.font = '10px Inter, system-ui, sans-serif';
  ctx.fillStyle = '#555555';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by X Algorithm Toolkit — github.com/Mr-Chartist/x-algo-toolkit', W / 2, y);

  // Export as PNG download
  canvas.toBlob((blob) => {
    if (!blob) { toast('error', 'Failed to generate image'); return; }
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `x-algo-scorecard-${data.score}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast('success', 'Scorecard downloaded!');
  }, 'image/png');
}
